Repository cloud-bulldozer/benchmark-operator, pull requests merged in 2020-10, with the labels that each got.

#427 Option to send fio results to client pod log
  docs/fio_distributed.md
  roles/fio_distributed/templates/client.yaml
Labels: ok to test

#426 Allow passing workload.args.prom_es_user and prom_es_pass
  docs/kube-burner.md
  roles/kube-burner/templates/cluster-density.yml.j2
  roles/kube-burner/templates/kubelet-density-heavy.yml.j2
  roles/kube-burner/templates/kubelet-density.yml.j2
Labels: ok to test

#418 add pairs and multus_client to es
  roles/uperf/templates/workload.yml.j2
Labels: ok to test

#412 stressng integration
  README.md
  docs/stressng.md
  resources/crds/ripsaw_v1alpha1_stressng_cr.yaml
  roles/stressng/tasks/main.yaml
  roles/stressng/templates/jobfile.j2
  roles/stressng/templates/stressng_workload.yml.j2
  tests/common.sh
  tests/test_crs/valid_stressng.yaml
  tests/test_list
  tests/test_stressng.sh
Labels: ok to test

#434 supporting nodeSelector for byowl
  roles/byowl/templates/workload.yml
Labels: ok to test

#436 Rename the prometheus ES server|port|parallel to es_server|port|parallel
  docs/prometheus.md
  resources/crds/ripsaw_v1alpha1_ripsaw_crd.yaml
  roles/fio_distributed/templates/client.yaml
  roles/fs-drift/templates/workload_job.yml.j2
  roles/hammerdb/templates/db_mssql_workload.yml.j2
  roles/hammerdb/templates/db_mysql_workload.yml.j2
  roles/hammerdb/templates/db_postgres_workload.yml.j2
  roles/kube-burner/templates/cluster-density.yml.j2
  roles/kube-burner/templates/kubelet-density-heavy.yml.j2
  roles/kube-burner/templates/kubelet-density.yml.j2
  roles/pgbench/templates/workload.yml.j2
  roles/scale_openshift/templates/scale.yml
  roles/smallfile/templates/workload_job.yml.j2
  roles/stressng/templates/stressng_workload.yml.j2
  roles/uperf/templates/workload.yml.j2
  roles/vegeta/templates/vegeta.yml.j2
  roles/ycsb/templates/ycsb_load.yaml
  roles/ycsb/templates/ycsb_run.yaml
  tests/test_crs/valid_kube-burner.yaml
Labels: ok to test

#439 Fixing doc and kube-burner cr for updated prometheus.es_server
  docs/kube-burner.md
  resources/crds/ripsaw_v1alpha1_kube-burner_cr.yaml
Labels: ok to test

#440 container_memory_rss instead memory_usage.
  roles/kube-burner/files/metrics-aggregated.yaml
  roles/kube-burner/files/metrics.yaml
  roles/kube-burner/tasks/main.yml
Labels: ok to test

#442 Fix global overrides
  resources/crds/ripsaw_v1alpha1_ripsaw_crd.yaml
  tests/test_backpack.sh
Labels: ok to test

#447 Installing git in uperf VMs
  roles/uperf/templates/server_vm.yml.j2
  roles/uperf/templates/workload_vm.yml.j2
Labels: bug

#448 Remove authentication ES parameters from kube-burner
  docs/kube-burner.md
  roles/kube-burner/templates/cluster-density.yml.j2
  roles/kube-burner/templates/kubelet-density-heavy.yml.j2
  roles/kube-burner/templates/kubelet-density.yml.j2
Labels: enhancement, ok to test

#456 Adding hexfusion's recommendations
  roles/kube-burner/files/metrics-aggregated.yaml
  roles/kube-burner/files/metrics.yaml
Labels: ok to test

#458 Add ConfigMaps to cluster-density kube-burner tests
  docs/kube-burner.md
  roles/kube-burner/files/configmap.yml
  roles/kube-burner/files/deployment.yml
  roles/kube-burner/tasks/main.yml
  roles/kube-burner/templates/cluster-density.yml.j2
Labels: ok to test

#441 Add documentation fixes
  docs/cache_dropping.md
  docs/scale_openshift.md
  docs/uperf.md
Labels: ok to test

#459 Update node selector in stressng job spec
  docs/stressng.md
  resources/crds/ripsaw_v1alpha1_stressng_cr.yaml
  roles/stressng/templates/stressng_workload.yml.j2
Labels: ok to test

#444 Append uuid to namespace name
  roles/kube-burner/templates/cluster-density.yml.j2
  roles/kube-burner/templates/kubelet-density-heavy.yml.j2
  roles/kube-burner/templates/kubelet-density.yml.j2
Labels: ok to test

#462 Smallfile cachedrop
  docs/cache_dropping.md
  roles/smallfile/templates/workload_job.yml.j2
  tests/test_smallfile.sh
Labels: ok to test
