Repository cloud-bulldozer/benchmark-operator, pull requests merged in 2020-07, with the labels that each got.

#366 Fix broken URLs
  build/Dockerfile
  image_resources/centos8-appstream.repo
Labels: ok to test

#367 Select only one pod in uperf service
  roles/uperf/templates/service.yml.j2
Labels: ok to test

#365 Update hammerdb workload to support reconciliation loop
  README.md
  roles/hammerdb/tasks/main.yaml
Labels: ok to test

#355 Fio in vms
  README.md
  docs/fio_distributed.md
  resources/crds/ripsaw_v1alpha1_fio_distributed_vm_cr.yaml
  roles/fio_distributed/defaults/main.yml
  roles/fio_distributed/tasks/main.yml
  roles/fio_distributed/templates/client.yaml
  roles/fio_distributed/templates/server_vm.yml.j2
Labels: ok to test

#369 Updating for new ci environment
  test.sh
  tests/common.sh
  tests/test_crs/valid_backpack.yaml
  tests/test_crs/valid_byowl.yaml
  tests/test_crs/valid_fiod.yaml
  tests/test_crs/valid_fiod_hostpath.yaml
  tests/test_crs/valid_fs_drift.yaml
  tests/test_crs/valid_fs_drift_hostpath.yaml
  tests/test_crs/valid_hammerdb.yaml
  tests/test_crs/valid_iperf3.yaml
  tests/test_crs/valid_pgbench.yaml
  tests/test_crs/valid_smallfile.yaml
  tests/test_crs/valid_smallfile_hostpath.yaml
  tests/test_crs/valid_sysbench.yaml
  tests/test_crs/valid_uperf.yaml
  tests/test_crs/valid_uperf_resources.yaml
  tests/test_crs/valid_uperf_serviceip.yaml
  tests/test_crs/valid_uperf_store.yaml
  tests/test_crs/valid_ycsb-mongo.yaml
Labels: ok to test

#359 Add vegeta benchmark
  README.md
  docs/vegeta.md
  resources/crds/ripsaw_v1alpha1_vegeta_cr.yaml
  roles/vegeta/tasks/main.yml
  roles/vegeta/templates/targets.yml.j2
  roles/vegeta/templates/vegeta.yml.j2
  tests/common.sh
  tests/test_crs/valid_vegeta.yaml
  tests/test_crs/valid_vegeta_hostnetwork.yaml
  tests/test_list
  tests/test_vegeta.sh
Labels: enhancement, ok to test

#370 Allow passing of additional arguments to test.sh
  test.sh
Labels: ok to test

#343 Updated roles to use snafu as a package
  roles/fio_distributed/templates/client.yaml
  roles/fs-drift/templates/workload_job.yml.j2
  roles/hammerdb/templates/db_workload.yml.j2
  roles/pgbench/templates/workload.yml.j2
  roles/smallfile/templates/workload_job.yml.j2
  roles/uperf/templates/workload.yml.j2
  roles/ycsb/templates/ycsb_load.yaml
  roles/ycsb/templates/ycsb_run.yaml
Labels: enhancement, ok to test

#373 Use pip installed Vegeta
  roles/vegeta/templates/vegeta.yml.j2
Labels: ok to test

#372 Updating CI test script to create unique crd names for each run
  test.sh
  tests/test_pgbench.sh
  tests/test_ycsb.sh
Labels: CI, ok to test

#371 Add further PVC options to the fio workload
  docs/fio_distributed.md
  resources/crds/ripsaw_v1alpha1_fio_distributed_vm_cr.yaml
  roles/fio_distributed/tasks/main.yml
Labels: ok to test
