Repository cloud-bulldozer/benchmark-operator, pull requests merged in 2021-01, with the labels that each got.

#511 Add node name to environment variables
  roles/uperf/templates/workload.yml.j2
Labels: ok to test

#507 Enable ssl verification for Elasticsearch in Backpack
  docs/metadata.md
  resources/crds/ripsaw_v1alpha1_ripsaw_crd.yaml
  roles/backpack/templates/backpack.yml
  templates/metadata.yml.j2
Labels: ok to test

#513 Fixing populate function for iperf
  tests/common.sh
Labels: ok to test

#509 Add Iperf3 pod anti-affinity rules
  roles/iperf3/templates/client.yml.j2
  roles/iperf3/templates/client_store.yml.j2
  roles/iperf3/templates/server.yml.j2
Labels: ok to test

#516 Convert ripsaw crd from chart into a symbolic link
  charts/benchmark-operator/crds/ripsaw_v1alpha1_ripsaw_crd.yaml
Labels: bug

#518 Add missing space between nodeSelector key and value
  roles/fio_distributed/templates/servers.yaml
Labels: bug, ok to test
