Repository cloud-bulldozer/benchmark-operator, pull requests merged in 2021-09, with the labels that each got.

#665 Elasticsearch URL
  config/crd/bases/ripsaw.cloudbulldozer.io_benchmarks.yaml
  roles/cyclictest/templates/cyclictestjob.yaml
  roles/fio_distributed/templates/client.yaml
  roles/flent/templates/workload.yml.j2
  roles/fs-drift/templates/workload_job.yml.j2
  roles/hammerdb/templates/db_mariadb_workload.yml.j2
  roles/hammerdb/templates/db_mariadb_workload_vm.sh.j2
  roles/hammerdb/templates/db_mssql_workload.yml.j2
  roles/hammerdb/templates/db_mssql_workload_vm.sh.j2
  roles/hammerdb/templates/db_postgres_workload.yml.j2
  roles/hammerdb/templates/db_postgres_workload_vm.sh.j2
  roles/image_pull/templates/image_pull.yml
  roles/log_generator/templates/log_generator.yml
  roles/oslat/templates/oslatjob.yaml
  roles/pgbench/templates/workload.yml.j2
  roles/scale_openshift/templates/scale.yml
  roles/smallfile/templates/workload_job.yml.j2
  roles/stressng/templates/stressng_workload.yml.j2
  roles/stressng/templates/stressng_workload_vm.yml.j2
  roles/testpmd/templates/trex.yml.j2
  roles/uperf/templates/configmap_script.yml.j2
  roles/uperf/templates/workload.yml.j2
  roles/vegeta/templates/vegeta.yml.j2
  roles/ycsb/templates/ycsb_load.yaml
  roles/ycsb/templates/ycsb_run.yaml
Labels: bug, ok to test

#655 UPERF: Fix node name truncation to avoid ending with a dot '.' char
  roles/uperf/templates/server.yml.j2
  roles/uperf/templates/service.yml.j2
Labels: ok to test

#667 Fix not targeted metadata collection
  roles/backpack/tasks/main.yml
Labels: bug, enhancement, ok to test

#669 Removing default value for image_name as it was causing the real defa…
  config/crd/bases/ripsaw.cloudbulldozer.io_benchmarks.yaml
Labels: ok to test

#666 Fio no log hist
  docs/fio_distributed.md
  roles/fio_distributed/templates/configmap.yml.j2
  tests/test_crs/valid_fiod_bsrange.yaml
  tests/test_crs/valid_fiod_hostpath.yaml
Labels: ok to test

#670 Add a nodeSelector for vegeta pods
  config/samples/vegeta/cr.yaml
  docs/vegeta.md
  roles/vegeta/templates/vegeta.yml.j2
Labels: enhancement, ok to test

#678 Vm complete state
  roles/uperf/tasks/send_client_run_signal.yml
Labels: ok to test

#652 Smallfile cr params
  config/samples/smallfile/cr.yaml
  docs/smallfile.md
  roles/smallfile/templates/smallfilejob.other_parameters.yaml.j2
  roles/smallfile/templates/workload_job.yml.j2
  tests/test_crs/valid_smallfile.yaml
Labels: ok to test

#684 add rosa parameters to scale template
  docs/scale_openshift.md
  roles/scale_openshift/templates/scale.yml
Labels: enhancement, ok to test

#680 Cleanup delay pass to smf
  roles/smallfile/templates/smallfilejob.other_parameters.yaml.j2
  tests/test_crs/valid_smallfile.yaml
Labels: ok to test

#686 Improve vegeta synchronization
  roles/vegeta/templates/vegeta.yml.j2
  tests/test_crs/valid_vegeta.yaml
Labels: enhancement, ok to test, CI

#688 Concurrency for e2e workflow
  .github/workflows/e2e.yml
Labels: enhancement
