Repository cloud-bulldozer/benchmark-operator, pull requests merged in 2021-07, with the labels that each got.

#599 fix svc name to not include period
  roles/uperf/templates/service.yml.j2
Labels: ok to test

#600 Update namespace count query
  roles/kube-burner/files/metrics-aggregated.yaml
  roles/kube-burner/files/metrics.yaml
Labels: bug, ok to test

#593 add alerts to kube-burner dash
  roles/kube-burner/files/metrics-aggregated.yaml
  roles/kube-burner/files/metrics.yaml
Labels: ok to test

#604 Update metric profiles to new schema
  max-namespaces.yml
  roles/kube-burner/files/metrics-aggregated.yaml
  roles/kube-burner/files/metrics.yaml
Labels: ok to test

#610 Add cri-o network setup latency metrics
  roles/kube-burner/files/metrics-aggregated.yaml
  roles/kube-burner/files/metrics.yaml
Labels: enhancement, ok to test

#606 Stressng
  config/samples/stressng/cr.yaml
  config/samples/stressng/vm-cr.yaml
  roles/stressng/templates/stressng_workload.yml.j2
  roles/stressng/templates/stressng_workload_vm.yml.j2
Labels: ok to test

#618 Add container granurality to metrics
  roles/kube-burner/files/metrics-aggregated.yaml
  roles/kube-burner/files/metrics.yaml
Labels: enhancement, ok to test

#620 Arbitrary env vars to kube-burner
  docs/kube-burner.md
  roles/kube-burner/tasks/main.yml
  roles/kube-burner/templates/kube-burner.yml.j2
Labels: enhancement, ok to test

#622 Extra env vars as dictionary rather than a list of dictionaries
  docs/kube-burner.md
  roles/kube-burner/templates/kube-burner.yml.j2
Labels: enhancement, ok to test

#621 Fix uuid error
  playbooks/benchmark.yml
  roles/uuid/tasks/main.yml
Labels: bug, ok to test

#623 Lower reconcilePeriod
  watches.yaml
Labels: bug, enhancement, ok to test

#588 add networkpolicy cases for kube-burner
  roles/kube-burner/files/case2-networkpolicy.yaml
  roles/kube-burner/files/case3-networkpolicy.yaml
  roles/kube-burner/files/cross-ns-networkpolicy.yaml
  roles/kube-burner/files/networkpolicy-deny-all.yaml
  roles/kube-burner/files/networkpolicy-ingress.yaml
  roles/kube-burner/files/networkpolicy-monitoring.yaml
  roles/kube-burner/files/networkpolicy-same-ns.yaml
  roles/kube-burner/files/nginx-cross-ns.yaml
  roles/kube-burner/files/nginx.yaml
  roles/kube-burner/tasks/main.yml
  roles/kube-burner/templates/networkpolicy-case2.yml.j2
  roles/kube-burner/templates/networkpolicy-case3.yml.j2
  roles/kube-burner/templates/networkpolicy-cross-ns.yml.j2
  roles/kube-burner/templates/networkpolicy-multitenant.yml.j2
Labels: ok to test
