Repository cloud-bulldozer/benchmark-operator, pull requests merged in 2021-03, with the labels that each got.

#528 Add pod-density scenarios
  docs/kube-burner.md
  roles/kube-burner/tasks/main.yml
  roles/kube-burner/templates/node-pod-density.yml.j2
Labels: ok to test

#410 Flent workload
  README.md
  docs/flent.md
  resources/crds/ripsaw_v1alpha1_flent_cr.yaml
  roles/flent/README.md
  roles/flent/meta/main.yml
  roles/flent/tasks/main.yml
  roles/flent/templates/server.yml.j2
  roles/flent/templates/service.yml.j2
  roles/flent/templates/workload.yml.j2
  roles/flent/vars/main.yml
  tests/common.sh
  tests/test_crs/valid_flent.yaml
  tests/test_crs/valid_flent_resources.yaml
  tests/test_flent.sh
  tests/test_list
Labels: ok to test

#546 Adding debug workload option for snafu related jobs and enabling it for CI
  README.md
  roles/cyclictest/templates/cyclictestjob.yaml
  roles/fio_distributed/templates/client.yaml
  roles/flent/templates/workload.yml.j2
  roles/fs-drift/templates/workload_job.yml.j2
  roles/hammerdb/templates/db_mssql_workload.yml.j2
  roles/hammerdb/templates/db_mysql_workload.yml.j2
  roles/hammerdb/templates/db_postgres_workload.yml.j2
  roles/oslat/templates/oslatjob.yaml
  roles/pgbench/templates/workload.yml.j2
  roles/scale_openshift/templates/scale.yml
  roles/smallfile/templates/workload_job.yml.j2
  roles/stressng/templates/stressng_workload.yml.j2
  roles/stressng/templates/stressng_workload_vm.yml.j2
  roles/testpmd/templates/trex.yml.j2
  roles/uperf/templates/configmap_script.yml.j2
  roles/uperf/templates/workload.yml.j2
  roles/vegeta/templates/vegeta.yml.j2
  roles/ycsb/templates/ycsb_load.yaml
  roles/ycsb/templates/ycsb_run.yaml
  tests/test_crs/valid_fiod.yaml
  tests/test_crs/valid_fiod_bsrange.yaml
  tests/test_crs/valid_fiod_hostpath.yaml
  tests/test_crs/valid_flent.yaml
  tests/test_crs/valid_flent_resources.yaml
  tests/test_crs/valid_fs_drift.yaml
  tests/test_crs/valid_fs_drift_hostpath.yaml
  tests/test_crs/valid_hammerdb.yaml
  tests/test_crs/valid_pgbench.yaml
  tests/test_crs/valid_scale_down.yaml
  tests/test_crs/valid_scale_up.yaml
  tests/test_crs/valid_smallfile.yaml
  tests/test_crs/valid_smallfile_hostpath.yaml
  tests/test_crs/valid_stressng.yaml
  tests/test_crs/valid_uperf.yaml
  tests/test_crs/valid_uperf_networkpolicy.yaml
  tests/test_crs/valid_uperf_resources.yaml
  tests/test_crs/valid_uperf_serviceip.yaml
  tests/test_crs/valid_vegeta.yaml
  tests/test_crs/valid_vegeta_hostnetwork.yaml
  tests/test_crs/valid_ycsb-mongo.yaml
Labels: ok to test

#550 Remove iperf3 compulsory arguments
  roles/iperf3/templates/client.yml.j2
  roles/iperf3/templates/client_store.yml.j2
  roles/iperf3/templates/server.yml.j2
Labels: enhancement, ok to test

#551 Truncate UPERF node names to 27 chars max.
  roles/uperf/templates/server.yml.j2
  roles/uperf/templates/service.yml.j2
Labels: ok to test

#556 Add more metrics to capture during the kube-burner runs
  roles/kube-burner/files/metrics-aggregated.yaml
  roles/kube-burner/files/metrics.yaml
Labels: P2, ok to test
