Repository cloud-bulldozer/benchmark-operator, pull requests merged in 2021-08, with the labels that each got.

#624 Fix system-metrics collection
  roles/system-metrics/tasks/main.yml
  roles/system-metrics/templates/kube-burner.yml.j2
  roles/system-metrics/templates/node-metrics.yml
Labels: bug, ok to test

#613 Container build mechanism
  .github/workflows/release.yml
  Dockerfile
  Makefile
  README.md
  charts/benchmark-operator/README.md
  charts/benchmark-operator/values.yaml
  hack/tag_name.sh
  image_resources/centos8-appstream.repo
  tests/common.sh
Labels: enhancement, ok to test

#612 Backpack needs a RW root
  playbooks/templates/metadata.yml.j2
  roles/backpack/templates/backpack.yml
Labels: ok to test

#626 Use IMG to push the image
  Makefile
Labels: bug

#630 Stressng: add vm completed state
  roles/stressng/templates/stressng_workload_vm.yml.j2
Labels: bug

#632 Hammerdb vm completed
  roles/hammerdb/templates/db_creation_mariadb_vm.yml
  roles/hammerdb/templates/db_creation_mssql_vm.yml
  roles/hammerdb/templates/db_creation_postgres_vm.yml
  roles/hammerdb/templates/db_mariadb_workload_vm.sh.j2
  roles/hammerdb/templates/db_mssql_workload_vm.sh.j2
  roles/hammerdb/templates/db_postgres_workload_vm.sh.j2
Labels: bug, enhancement

#633 --show-current flag is not available for git versions < 2.22
  Makefile
  hack/tag_name.sh
Labels: bug

#628 remove if from populate_test_list function
  tests/common.sh
Labels: ok to test

#627 fio prefill should use same numjobs value as fio samples
  roles/fio_distributed/templates/configmap.yml.j2
Labels: bug, ok to test

#597 Smf cleanup delay
  roles/smallfile/templates/smallfilejob.other_parameters.yaml.j2
  tests/test_crs/valid_smallfile.yaml
Labels: ok to test

#634 Remove IMG_ARCH references
  .github/workflows/release.yml
  Makefile
Labels: bug, ok to test

#636 Deprecate cerberus integration
  README.md
  config/crd/bases/ripsaw.cloudbulldozer.io_benchmarks.yaml
  docs/cerberus.md
  docs/testpmd.md
  playbooks/benchmark.yml
  roles/benchmark_state/tasks/failure.yml
  roles/cerberus/tasks/main.yml
Labels: ok to test

#617 Ripsaw CLI
  .github/workflows/cli.unit.yml
  .gitignore
  .pre-commit-config.yaml
  cli/.coveragerc
  cli/.flake8
  cli/.pylintrc
  cli/MANIFEST.in
  cli/README.md
  cli/pytest.ini
  cli/ripsaw/__init__.py
  cli/ripsaw/cli.py
  cli/ripsaw/clients/__init__.py
  cli/ripsaw/clients/elastic.py
  cli/ripsaw/clients/k8s.py
  cli/ripsaw/commands/__init__.py
  cli/ripsaw/commands/benchmark.py
  cli/ripsaw/commands/operator.py
  cli/ripsaw/models/__init__.py
  cli/ripsaw/models/benchmark.py
  cli/ripsaw/models/workload.py
  cli/ripsaw/util/__init__.py
  cli/ripsaw/util/exceptions.py
  cli/ripsaw/util/logging.py
  cli/setup.cfg
  cli/setup.py
  cli/tests/__init__.py
  cli/tests/clients/test_elastic.py
  cli/tests/clients/test_k8s.py
  cli/tests/commands/test_benchmark_commands.py
  cli/tests/commands/test_operator_commands.py
  cli/tests/conftest.py
  cli/tests/models/test_benchmark.py
  cli/tests/models/test_workload.py
  cli/tests/resources/benchmark.yaml
  cli/tests/resources/job.yaml
  cli/tox.ini
  cli/version.txt
  config/manager/manager.yaml
Labels: ok to test

#643 Small CR iperf3 CR change & docs update
  CONTRIBUTING.md
  Makefile
  README.md
  config/manager/kustomization.yaml
  config/samples/iperf3/cr.yaml
  docs/cyclictest.md
  docs/elastic.md
  docs/fio_distributed.md
  docs/flent.md
  docs/fs-drift.md
  docs/iperf3.md
  docs/oslat.md
  docs/smallfile.md
  docs/sysbench.md
  docs/uperf.md
  docs/ycsb.md
Labels: ok to test

#662 Able to run the sysbench test on a specific node
  config/samples/sysbench/cr.yaml
  docs/sysbench.md
  roles/sysbench/templates/workload.yml
Labels: ok to test

#664 Set restartPolicy Never to all jobs deployed by benchmark-operator
  roles/byowl/templates/workload.yml
  roles/flent/templates/workload.yml.j2
  roles/hammerdb/templates/db_creation.yml
  roles/hammerdb/templates/db_mariadb_workload.yml.j2
  roles/hammerdb/templates/db_mssql_workload.yml.j2
  roles/hammerdb/templates/db_postgres_workload.yml.j2
  roles/iperf3/templates/client.yml.j2
  roles/iperf3/templates/client_store.yml.j2
  roles/iperf3/templates/server.yml.j2
  roles/pgbench/templates/workload.yml.j2
  roles/stressng/templates/stressng_workload.yml.j2
  roles/sysbench/templates/workload.yml
  roles/testpmd/templates/testpmd.yml.j2
  roles/testpmd/templates/trex.yml.j2
  roles/uperf/templates/workload.yml.j2
  roles/vegeta/templates/vegeta.yml.j2
Labels: bug, ok to test
