Repository cloud-bulldozer/benchmark-operator, pull requests merged in 2022-08, with the labels that each got.

#781 Use uperf pod antiAffinity rules
  docs/uperf.md
  roles/uperf/tasks/main.yml
  roles/uperf/templates/server.yml.j2
  roles/uperf/templates/workload.yml.j2
Labels: enhancement, ok to test, not_ready

#778 updated README.md
  README.md
Labels: not_ready

#734 SCTP support for pod2service scenarios in uperf workloads
  docs/uperf.md
  e2e/uperf/uperf.yaml
  e2e/uperf/uperf_serviceip.yaml
  roles/uperf/templates/service.yml.j2
  roles/uperf/templates/service_metallb.yml.j2
Labels: enhancement, ok to test

#795 Benchmark-operator's affinity preference to workload node
  config/manager/manager.yaml
Labels: enhancement, ok to test
